# Generated by Django 3.2 on 2021-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=10)),
                ('storage', models.CharField(max_length=10)),
                ('price', models.FloatField(max_length=10)),
                ('stock', models.IntegerField(max_length=5)),
            ],
        ),
    ]
